package ical

// THIS FILE IS AUTO-GENERATED BY internal/cmd/gentypes/gentypes.go
// DO NOT EDIT. ALL CHANGES WILL BE LOST

import (
	"bytes"
	"strings"

	"github.com/pkg/errors"
)

type Todo struct {
	entries EntryList
	props   *PropertySet
}

func NewTodo() *Todo {
	return &Todo{
		props: NewPropertySet(),
	}
}

func (v *Todo) String() string {
	var buf bytes.Buffer
	NewEncoder(&buf).Encode(v)
	return buf.String()
}

func (v Todo) Type() string {
	return "VTODO"
}

func (v *Todo) Entries() <-chan Entry {
	return v.entries.Iterator()
}

func (v *Todo) GetProperty(name string) (*Property, bool) {
	return v.props.GetFirst(name)
}

func (v *Todo) Properties() <-chan *Property {
	return v.props.Iterator()
}

func (v *Todo) AddProperty(key, value string, options ...PropertyOption) error {
	var params Parameters
	var force bool
	for _, option := range options {
		switch option.Name() {
		case "Parameters":
			params = option.Get().(Parameters)
		case "Force":
			force = option.Get().(bool)
		}
	}

	switch key = strings.ToLower(key); key {
	case "class", "completed", "created", "description", "dtstamp", "dtstart", "due", "duration", "geo", "last-modified", "location", "organizer", "percent-complete", "priority", "recurrence-id", "sequence", "status", "summary", "uid", "url":
		v.props.Set(NewProperty(key, value, params))
	case "attach", "attendee", "categories", "comment", "contact", "exdate", "exrule", "request-status", "related-to", "resources", "rdate", "rrule":
		v.props.Append(NewProperty(key, value, params))
	default:
		if strings.HasPrefix(key, "x-") || force {
			v.props.Append(NewProperty(key, value, params))
		} else {
			return errors.Errorf(`invalid property %s`, key)
		} /* end if */
	}
	return nil
}
