name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Go stable version
        if: matrix.go != 'tip'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test 
        run: go test -v ./... 
      - name: Upload code coverage to codecov
        if: matrix.go == '1.15'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out

